// Generated by the ProjectIt Language Generator.
import { PiProjection, PiActions, PiTyperPart, PiStdlib } from "@projectit/core";
import { CustomLIonCoreActions, CustomLIonCoreProjection } from "../editor";
import { CustomLIonCoreTyperPart } from "../typer";
import { CustomLIonCoreValidator } from "../validator";
import { CustomLIonCoreStdlib } from "../stdlib";
import { LIonCoreCheckerInterface } from "../validator/gen";

/**
 * Class ProjectitConfiguration is the place where you can add all your customisations.
 * These will be used through the 'projectitConfiguration' constant by any generated
 * part of your language environment.
 */
class ProjectitConfiguration {
    // add your custom editor projections here
    customProjection: PiProjection[] = [new CustomLIonCoreProjection("manual")];
    // add your custom editor actions here
    customActions: PiActions[] = [new CustomLIonCoreActions()];
    // add your custom validations here
    customValidations: LIonCoreCheckerInterface[] = [new CustomLIonCoreValidator()];
    // add your custom type-providers here
    customTypers: PiTyperPart[] = [new CustomLIonCoreTyperPart()];
    // add extra predefined instances here
    customStdLibs: PiStdlib[] = [new CustomLIonCoreStdlib()];
}

export const projectitConfiguration = new ProjectitConfiguration();
