// Generated by the ProjectIt Language Generator.
import { PiError, PiErrorSeverity } from "@projectit/core";
import { LIonCoreDefaultWorker } from "../utils/gen/LIonCoreDefaultWorker";
import { LIonCoreCheckerInterface } from "./gen/LIonCoreValidator";

export class CustomLIonCoreValidator extends LIonCoreDefaultWorker implements LIonCoreCheckerInterface {
    errorList: PiError[] = [];
}
